<a href="https://colab.research.google.com/github/sanveg-rane-13/machine_learning_basics/blob/master/Keras_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Train deep neural networks with Keras and evaluate them**

# Basic keras NN

In [0]:
import tensorflow as tf
import numpy as np

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, LSTM
from tensorflow.keras import losses, optimizers, metrics

**Basic Keras layer**

- Input layer, Hidden layer and Output layer

In [0]:
model = Sequential()

input_layer = Dense(32, activation='relu', input_shape=(8,))
model.add(input_layer)

hidden_layer = Dense(64, activation='relu')
model.add(hidden_layer)

output_layer = Dense(8)
model.add(output_layer)

In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                288       
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 520       
Total params: 2,920
Trainable params: 2,920
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer = 'sgd', 
              loss = 'mean_squared_error', 
              metrics = [metrics.categorical_accuracy])

**Creating data**
- creating random data using numpy
- creating random validation data

In [0]:
x_train = np.random.random((10,10,10)) 
y_train = np.random.random((10,10))

In [0]:
x_val = np.random.random((10,10,10)) 
y_val = np.random.random((10,10))

In [0]:
epochs = 5
batch_size = 32

**Building a simple model**

In [0]:
lstm_model = Sequential()

In [0]:
lstm_model.add(Dense(16, activation = 'relu', input_shape=(10,10)))
lstm_model.add(LSTM(16, return_sequences = True))
lstm_model.add(Dense(10, activation = 'softmax'))

In [0]:
lstm_model.compile(loss = 'categorical_crossentropy',
                   optimizer = 'sgd',
                   metrics = ['accuracy'])

In [0]:
lstm_model.fit(x_train, y_train, batch_size = batch_size, epochs = epochs, validation_data = (x_val, y_val))

# Multi layer perceptron ANN

In [0]:
import tensorflow as tf
import numpy as np

from tensorflow import keras
from tensorflow.keras import layers, losses, optimizers, metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, Dropout
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.datasets import mnist

**Input Dataset module**

1.   Load MNIST database of handwritten digits
2.   Process the data


In [0]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
x_train = x_train.reshape(60000, 784) 
x_test = x_test.reshape(10000, 784) 
x_train = x_train.astype('float32') 
x_test = x_test.astype('float32') 
x_train /= 255 
x_test /= 255

y_train = keras.utils.to_categorical(y_train, 10) 
y_test = keras.utils.to_categorical(y_test, 10)

**Creating the model**

Layers in the network:
- Input layer - 784 features with input and weights
- Hidden layer 1 - 512 neurons and relu activation, add a dropout
- Hidden layer 2 - 512 neurons and relu activation, add a dropout
- Output layer - 10 classifications and softmax activation

In [0]:
model = Sequential()

In [0]:
model.add(Dense(512, activation = 'relu', input_shape = (784,)))
model.add(Dropout(0.2))

model.add(Dense(512, activation = 'relu'))
model.add(Dropout(0.2))

model.add(Dense(10, activation = 'softmax'))

**Building the model**
- Loss function - categorical_crossentropy
- Optimization funtion - RMSprop

In [0]:
model.compile(
    loss = 'categorical_crossentropy',
    optimizer = RMSprop(),
    metrics = ['accuracy']
)

**Training the model**

In [0]:
batch_size = 128
epochs = 20

In [0]:
trained_model = model.fit(
    x_train, y_train,
    batch_size = batch_size,
    epochs = epochs,
    verbose = 1,
    validation_data = (x_test, y_test)
)

Epoch 1/20
469/469 [==============================] - 9s 19ms/step - loss: 0.2459 - accuracy: 0.9242 - val_loss: 0.1170 - val_accuracy: 0.9636
Epoch 2/20
469/469 [==============================] - 9s 18ms/step - loss: 0.1027 - accuracy: 0.9695 - val_loss: 0.0856 - val_accuracy: 0.9738
Epoch 3/20
469/469 [==============================] - 9s 18ms/step - loss: 0.0752 - accuracy: 0.9770 - val_loss: 0.0737 - val_accuracy: 0.9794
Epoch 4/20
469/469 [==============================] - 9s 18ms/step - loss: 0.0611 - accuracy: 0.9816 - val_loss: 0.0707 - val_accuracy: 0.9810
Epoch 5/20
469/469 [==============================] - 9s 18ms/step - loss: 0.0509 - accuracy: 0.9844 - val_loss: 0.0649 - val_accuracy: 0.9825
Epoch 6/20
469/469 [==============================] - 9s 19ms/step - loss: 0.0429 - accuracy: 0.9872 - val_loss: 0.0729 - val_accuracy: 0.9821
Epoch 7/20
469/469 [==============================] - 9s 18ms/step - loss: 0.0360 - accuracy: 0.9886 - val_loss: 0.0775 - val_accuracy: 0.9812

**Evaluating the model**
- The tesing accuracy and the loss function value

In [0]:
score = model.evaluate(x_test, y_test, verbose=0)

print("Testing loss: {0:.2%}".format(score[0]))
print("Testing accuracy: {0:.2%}".format(score[1]))

Testing loss: 11.44%
Testing accuracy: 98.46%


**Predictions using the model**

- Predicting the first five values in test data

In [0]:
pred = model.predict(x_test)

predicted_val = np.argmax(pred, axis = 1)[:5]
actual_val = np.argmax(y_test, axis = 1)[:5]

print(predicted_val)
print(actual_val)

[7 2 1 0 4]
[7 2 1 0 4]


# Convolutional Neural Network

Converting the digit identification problem from MLP to CNN


In [0]:
import tensorflow as tf
import numpy as np

from tensorflow import keras
from tensorflow.keras import backend as K
from tensorflow.keras import layers, losses, optimizers, metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPool2D
from tensorflow.keras.optimizers import Adadelta
from tensorflow.keras.datasets import mnist

**Loading data**

In [0]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

**Processing the data**
- processing data to feed to the model

In [0]:
img_rows, img_cols = 28, 28

if K.image_data_format() == 'channels_first':
  x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
  x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
  input_shape = (1, img_rows, img_cols)

else:
  x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
  x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
  input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32') 
x_test = x_test.astype('float32') 
x_train /= 255 
x_test /= 255

y_train = keras.utils.to_categorical(y_train, 10) 
y_test = keras.utils.to_categorical(y_test, 10)

**Creating model**

- Input layer
- Convolutional layer 1 - shape: 1,28,28; activation: relu; neurons: 32
- Convolutional layer 2 - activation: relu, neurons: 64
- Pooling layer 1 - pool size: 2,2
- Dropout layer
- Flatten - flatten all inputs to single dimension
- Dense layer - 128 neurons, activation: relu
- Dropout layer
- Output layer - 10 classifications , activation: softmax

In [0]:
cnn_model = Sequential()

In [0]:
cnn_model.add(Conv2D(32, input_shape = input_shape, activation = 'relu', kernel_size = (3,3)))
cnn_model.add(Conv2D(64, activation = 'relu', kernel_size = (3,3)))
cnn_model.add(MaxPool2D(pool_size = (2,2)))
cnn_model.add(Dropout(0.25))
cnn_model.add(Flatten())
cnn_model.add(Dense(128, activation = 'relu'))
cnn_model.add(Dropout(0.5))
cnn_model.add(Dense(10, activation = 'softmax'))

**Building the model**
- Loss function - categorical_crossentropy
- Optimization funtion - Ada delta

In [0]:
cnn_model.compile(
    loss = 'categorical_crossentropy',
    optimizer = RMSprop(),
    metrics = ['accuracy']
)

**Training the model**

In [0]:
batch_size = 128
epochs = 12
verbose = 1 # generated logs

In [15]:
cnn_model.fit(
    x_train, y_train,
    batch_size = batch_size,
    epochs = epochs,
    verbose = verbose,
    validation_data = (x_test, y_test)
)

Epoch 1/12
469/469 [==============================] - 5s 11ms/step - loss: 0.2229 - accuracy: 0.9316 - val_loss: 0.0645 - val_accuracy: 0.9782
Epoch 2/12
469/469 [==============================] - 5s 11ms/step - loss: 0.0817 - accuracy: 0.9757 - val_loss: 0.0420 - val_accuracy: 0.9866
Epoch 3/12
469/469 [==============================] - 5s 11ms/step - loss: 0.0650 - accuracy: 0.9810 - val_loss: 0.0342 - val_accuracy: 0.9889
Epoch 4/12
469/469 [==============================] - 5s 11ms/step - loss: 0.0547 - accuracy: 0.9840 - val_loss: 0.0347 - val_accuracy: 0.9895
Epoch 5/12
469/469 [==============================] - 5s 11ms/step - loss: 0.0484 - accuracy: 0.9864 - val_loss: 0.0347 - val_accuracy: 0.9897
Epoch 6/12
469/469 [==============================] - 5s 11ms/step - loss: 0.0467 - accuracy: 0.9864 - val_loss: 0.0312 - val_accuracy: 0.9903
Epoch 7/12
469/469 [==============================] - 5s 11ms/step - loss: 0.0468 - accuracy: 0.9866 - val_loss: 0.0290 - val_accuracy: 0.9899

**Evaluating the model**

In [16]:
score = cnn_model.evaluate(x_test, y_test, verbose=0)

print("Testing loss: {0:.2%}".format(score[0]))
print("Testing accuracy: {0:.2%}".format(score[1]))

Testing loss: 4.64%
Testing accuracy: 99.03%


**Predictions using the model**

- Predicting the first five values in test data

In [17]:
pred = cnn_model.predict(x_test)

predicted_val = np.argmax(pred, axis = 1)[:5]
actual_val = np.argmax(y_test, axis = 1)[:5]

print(predicted_val)
print(actual_val)

[7 2 1 0 4]
[7 2 1 0 4]
